[paths]
; quotes, trailink slash, spaces around are not important (anyway will be removed); environment variables may be used (CMD or PS syntax)
; savepath — where KSP saves are stored (must contain "Saves", "Screenshots" and "thumbs" directories)
savepath  = "G:\Saves\KSP"
; tmplpath — where settings as files ar stored (must contain "GameData" and "Saves" directories, "GameData.json", "Saves.json" and settings_%locale%.cfg files)
tmplpath  = "G:\Backup\KSP\templates"
; kmlpaths — where KML utility (KML.exe) is located; if no .exe filename set (just directory), "KML.exe" will be added
kmlpath   = "G:\Saves\KSP\utilities"
; cachepath — where CKAN cache is located
cachepath = "%LOCALAPPDATA%\CKAN\downloads"
